<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gao Ya &amp; Wang Yaling">

<title>ISSS608-VAA - Take-home_Ex04</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="../../site_libs/datatables-binding-0.31/datatables.js"></script>
<script src="../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS608-VAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html" rel="" target="">
 <span class="dropdown-text">Take-home Exercise 4</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">1 Getting Started</a>
  <ul class="collapse">
  <li><a href="#download-data" id="toc-download-data" class="nav-link" data-scroll-target="#download-data">1.1 Download Data</a></li>
  <li><a href="#load-r-packages" id="toc-load-r-packages" class="nav-link" data-scroll-target="#load-r-packages">1.2 Load R Packages</a></li>
  </ul></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">2 Data Preparation</a>
  <ul class="collapse">
  <li><a href="#import-data" id="toc-import-data" class="nav-link" data-scroll-target="#import-data">2.1 Import Data</a></li>
  <li><a href="#merge-data" id="toc-merge-data" class="nav-link" data-scroll-target="#merge-data">2.2 Merge Data</a></li>
  <li><a href="#extract-data" id="toc-extract-data" class="nav-link" data-scroll-target="#extract-data">2.3 Extract Data</a></li>
  <li><a href="#check-data-health" id="toc-check-data-health" class="nav-link" data-scroll-target="#check-data-health">2.4 Check Data Health</a></li>
  </ul></li>
  <li><a href="#save-data" id="toc-save-data" class="nav-link" data-scroll-target="#save-data">3 Save Data</a></li>
  <li><a href="#comfirmatory-data-analysis" id="toc-comfirmatory-data-analysis" class="nav-link" data-scroll-target="#comfirmatory-data-analysis">4. Comfirmatory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#load-processed-data" id="toc-load-processed-data" class="nav-link" data-scroll-target="#load-processed-data">4.1 Load Processed data</a></li>
  <li><a href="#distribution-of-numerical-categorical-variables" id="toc-distribution-of-numerical-categorical-variables" class="nav-link" data-scroll-target="#distribution-of-numerical-categorical-variables">4.2 Distribution of numerical &amp; categorical variables</a></li>
  <li><a href="#correlation-matrix-of-munerical-variables" id="toc-correlation-matrix-of-munerical-variables" class="nav-link" data-scroll-target="#correlation-matrix-of-munerical-variables">4.3 Correlation matrix of munerical variables</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">4.4 Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#anova-test-town-vs.-resale-price" id="toc-anova-test-town-vs.-resale-price" class="nav-link" data-scroll-target="#anova-test-town-vs.-resale-price">4.4.1 ANOVA test: Town vs.&nbsp;Resale Price</a></li>
  <li><a href="#non-parametric-test-of-town-and-flat-type" id="toc-non-parametric-test-of-town-and-flat-type" class="nav-link" data-scroll-target="#non-parametric-test-of-town-and-flat-type">4.4.2 Non-parametric Test of town and flat type</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">5. Clustering</a>
  <ul class="collapse">
  <li><a href="#k-means-clustering" id="toc-k-means-clustering" class="nav-link" data-scroll-target="#k-means-clustering">5.1 K-means clustering</a></li>
  <li><a href="#latent-clustering-analysis" id="toc-latent-clustering-analysis" class="nav-link" data-scroll-target="#latent-clustering-analysis">5.2 Latent Clustering Analysis</a></li>
  </ul></li>
  <li><a href="#decision-tree-analysis" id="toc-decision-tree-analysis" class="nav-link" data-scroll-target="#decision-tree-analysis">6 Decision tree Analysis</a>
  <ul class="collapse">
  <li><a href="#regression-tree" id="toc-regression-tree" class="nav-link" data-scroll-target="#regression-tree">6.1 Regression Tree</a></li>
  </ul></li>
  <li><a href="#shiny-app-prototype-design" id="toc-shiny-app-prototype-design" class="nav-link" data-scroll-target="#shiny-app-prototype-design">7. Shiny App Prototype Design</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home_Ex04</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gao Ya &amp; Wang Yaling </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">March 11, 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
NOTE
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our group decided to split the part in this Take-home Exercise. This Take-home Exercise will be focusing on data preparation, confirmatory data analysis, clustering and decision tree. While my group mate will be focusing on EDA and other parts.</p>
</div>
</div>
<section id="getting-started" class="level1">
<h1>1 Getting Started</h1>
<section id="download-data" class="level2">
<h2 class="anchored" data-anchor-id="download-data">1.1 Download Data</h2>
<p>The data is sourced from the <a href="https://www.kaggle.com/">Kaggle</a> dataset “<a href="https://www.kaggle.com/datasets/syrahmadi/resale-hdb-flat-prices-2000-2022?resource=download">Resale HDB Flat Prices 2012 - 2023</a>”, which comprises four CSV files as follows:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Dataset.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>The research for this project will be limited to the recent 10 years, from 01/01/2013 to 31/12/2023. Therefore, the required data files are the following three:</p>
<ul>
<li><p>resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014.csv</p></li>
<li><p>resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016.csv</p></li>
<li><p>ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv</p></li>
</ul>
</section>
<section id="load-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-r-packages">1.2 Load R Packages</h2>
<p>R packages required:</p>
<ul>
<li><p><strong>tidyverse</strong> for processing datasets, inside this package we will use:</p>
<ul>
<li><p><strong>readr</strong> for reading CSV files</p></li>
<li><p><strong>dplyr</strong> for operations such as filtering, selecting, transforming, summarizing, and joining data</p></li>
</ul></li>
<li><p><strong>DT</strong> for the creation of interactive HTML tables from R data frames</p></li>
<li><p><strong>summarytools</strong> for generating a descriptive statistical summary of the data frame</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, DT, summarytools,ggplot2,ggstatsplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="data-preparation" class="level1">
<h1>2 Data Preparation</h1>
<section id="import-data" class="level2">
<h2 class="anchored" data-anchor-id="import-data">2.1 Import Data</h2>
<p>The necessary .CSV files will be imported as a list of CSV files, then compiled into a single dataframe using R.</p>
<p>First, let’s take a look at the three CSV files and check their difference.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">mar-2012-to-dec-2014</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">jan-2015-to-dec-2016</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Jan-2017-onwards</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read .csv data files</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/resale-flat-prices-based-on-registration-date-from-mar-2012-to-dec-2014.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 52,203
Columns: 10
$ month               &lt;chr&gt; "2012-03", "2012-03", "2012-03", "2012-03", "2012-…
$ town                &lt;chr&gt; "ANG MO KIO", "ANG MO KIO", "ANG MO KIO", "ANG MO …
$ flat_type           &lt;chr&gt; "2 ROOM", "2 ROOM", "3 ROOM", "3 ROOM", "3 ROOM", …
$ block               &lt;chr&gt; "172", "510", "610", "474", "604", "154", "110", "…
$ street_name         &lt;chr&gt; "ANG MO KIO AVE 4", "ANG MO KIO AVE 8", "ANG MO KI…
$ storey_range        &lt;chr&gt; "06 TO 10", "01 TO 05", "06 TO 10", "01 TO 05", "0…
$ floor_area_sqm      &lt;dbl&gt; 45, 44, 68, 67, 67, 68, 67, 67, 67, 67, 68, 67, 68…
$ flat_model          &lt;chr&gt; "Improved", "Improved", "New Generation", "New Gen…
$ lease_commence_date &lt;int&gt; 1986, 1980, 1980, 1984, 1980, 1981, 1978, 1979, 19…
$ resale_price        &lt;dbl&gt; 250000, 265000, 315000, 320000, 321000, 321000, 32…</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read .csv data files</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/resale-flat-prices-based-on-registration-date-from-jan-2015-to-dec-2016.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 37,153
Columns: 11
$ month               &lt;chr&gt; "2015-01", "2015-01", "2015-01", "2015-01", "2015-…
$ town                &lt;chr&gt; "ANG MO KIO", "ANG MO KIO", "ANG MO KIO", "ANG MO …
$ flat_type           &lt;chr&gt; "3 ROOM", "3 ROOM", "3 ROOM", "3 ROOM", "3 ROOM", …
$ block               &lt;chr&gt; "174", "541", "163", "446", "557", "603", "709", "…
$ street_name         &lt;chr&gt; "ANG MO KIO AVE 4", "ANG MO KIO AVE 10", "ANG MO K…
$ storey_range        &lt;chr&gt; "07 TO 09", "01 TO 03", "01 TO 03", "01 TO 03", "0…
$ floor_area_sqm      &lt;dbl&gt; 60, 68, 69, 68, 68, 67, 68, 68, 67, 68, 67, 68, 68…
$ flat_model          &lt;chr&gt; "Improved", "New Generation", "New Generation", "N…
$ lease_commence_date &lt;int&gt; 1986, 1981, 1980, 1979, 1980, 1980, 1980, 1981, 19…
$ remaining_lease     &lt;int&gt; 70, 65, 64, 63, 64, 64, 64, 65, 62, 69, 60, 64, 65…
$ resale_price        &lt;dbl&gt; 255000, 275000, 285000, 290000, 290000, 290000, 29…</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read .csv data files</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 169,584
Columns: 11
$ month               &lt;chr&gt; "2017-01", "2017-01", "2017-01", "2017-01", "2017-…
$ town                &lt;chr&gt; "ANG MO KIO", "ANG MO KIO", "ANG MO KIO", "ANG MO …
$ flat_type           &lt;chr&gt; "2 ROOM", "3 ROOM", "3 ROOM", "3 ROOM", "3 ROOM", …
$ block               &lt;chr&gt; "406", "108", "602", "465", "601", "150", "447", "…
$ street_name         &lt;chr&gt; "ANG MO KIO AVE 10", "ANG MO KIO AVE 4", "ANG MO K…
$ storey_range        &lt;chr&gt; "10 TO 12", "01 TO 03", "01 TO 03", "04 TO 06", "0…
$ floor_area_sqm      &lt;dbl&gt; 44, 67, 67, 68, 67, 68, 68, 67, 68, 67, 68, 67, 67…
$ flat_model          &lt;chr&gt; "Improved", "New Generation", "New Generation", "N…
$ lease_commence_date &lt;int&gt; 1979, 1978, 1980, 1980, 1980, 1981, 1979, 1976, 19…
$ remaining_lease     &lt;chr&gt; "61 years 04 months", "60 years 07 months", "62 ye…
$ resale_price        &lt;dbl&gt; 232000, 250000, 262000, 265000, 265000, 275000, 28…</code></pre>
</div>
</div>
</div>
</div>
</div>
<div style="background-color: #E8EAF6;    border-radius: 10px;    padding: 20px;">
<p><strong>Observation from the above glimpse:</strong></p>
<ul>
<li><p>The data file “mar-2012-to-dec-2014” is missing the “remaining_lease” column.</p></li>
<li><p>The “remaining_lease” column in “jan-2015-to-dec-2016” is of integer data type.</p></li>
<li><p>The “remaining_lease” column in “Jan-2017-onwards” is of character data type.</p></li>
<li><p>All other column names and data types are identical across the three data files.</p></li>
</ul>
</div>
</section>
<section id="merge-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-data">2.2 Merge Data</h2>
<p>Before merging the three data files, the following steps need to be performed:</p>
<p>Step 1. Add a column named “remaining_lease” to the “mar-2012-to-dec-2014” data file.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formula of the column “remaining_lease”
</div>
</div>
<div class="callout-body-container callout-body">
<p>According to research, the tenure of Singapore HDB properties is 99 years.</p>
<p>Thus, the value of “remaining_lease” is calculated as 99 - (month - lease_commence_date). Note that “month” stands for the date of HDB resale in the datasets.</p>
</div>
</div>
<p>Step 2. Delete the original “remaining_lease” column in “jan-2015-to-dec-2016” and “Jan-2017-onwards” data file, and create new “remaining_lease” columns with the same formula as above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate remaining lease based on the provided formula</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease =</span> <span class="dv">99</span> <span class="sc">-</span> (<span class="fu">as.numeric</span>(<span class="fu">substr</span>(month, <span class="dv">1</span>, <span class="dv">4</span>)) <span class="sc">-</span> lease_commence_date))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># delete original remaining_lease column and create a new one</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>remaining_lease) <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease =</span> <span class="dv">99</span> <span class="sc">-</span> (<span class="fu">as.numeric</span>(<span class="fu">substr</span>(month, <span class="dv">1</span>, <span class="dv">4</span>)) <span class="sc">-</span> lease_commence_date))</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> data3 <span class="sc">%&gt;%</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>remaining_lease) <span class="sc">%&gt;%</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease =</span> <span class="dv">99</span> <span class="sc">-</span> (<span class="fu">as.numeric</span>(<span class="fu">substr</span>(month, <span class="dv">1</span>, <span class="dv">4</span>)) <span class="sc">-</span> lease_commence_date))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we can start merging the three files together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge data1, data2, and data3</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(data1, data2, data3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extract-data" class="level2">
<h2 class="anchored" data-anchor-id="extract-data">2.3 Extract Data</h2>
<p>To be able to extract the data from 2013 to 2023, we need to do the follow steps:</p>
<p>Step 1. Make sure the data type of column “month” is date-type.</p>
<p>Step 2. Extract data in 2013-2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert data type of "month" column to date</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="fu">paste0</span>(combined_data<span class="sc">$</span>month, <span class="st">"-01"</span>), <span class="at">format =</span> <span class="st">"%Y-%m-%d"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract data in 2013-2023</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>extract_data <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2013-01-01"</span>) <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="check-data-health" class="level2">
<h2 class="anchored" data-anchor-id="check-data-health">2.4 Check Data Health</h2>
<p>Now that we have a single dataframe, we first check the health of the dataframe by:</p>
<p>using <code>glimpse()</code> to look at the structure of the dataframe, data types of the columns, and some values of the dataframe,</p>
<p>using <code>datatable()</code> from the DT package to view the dataframe more interactively,</p>
<p>using <code>duplicate()</code> to check the dataframe for any duplicated entries using duplicate(),</p>
<p>using <code>summary()</code> to check the distribution of values,</p>
<p>using <code>descr()</code> to show the descriptive statistics of non-numerical variables.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">glimpse()</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">datatable()</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">duplicate()</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false">summary()</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-5" role="tab" aria-controls="tabset-2-5" aria-selected="false">descr()</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(extract_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 238,519
Columns: 11
$ month               &lt;date&gt; 2013-01-01, 2013-01-01, 2013-01-01, 2013-01-01, 2…
$ town                &lt;chr&gt; "ANG MO KIO", "ANG MO KIO", "ANG MO KIO", "ANG MO …
$ flat_type           &lt;chr&gt; "2 ROOM", "2 ROOM", "2 ROOM", "3 ROOM", "3 ROOM", …
$ block               &lt;chr&gt; "510", "314", "323", "170", "174", "445", "607", "…
$ street_name         &lt;chr&gt; "ANG MO KIO AVE 8", "ANG MO KIO AVE 3", "ANG MO KI…
$ storey_range        &lt;chr&gt; "01 TO 03", "01 TO 03", "04 TO 06", "07 TO 09", "0…
$ floor_area_sqm      &lt;dbl&gt; 44, 44, 44, 61, 60, 67, 68, 67, 68, 67, 74, 67, 68…
$ flat_model          &lt;chr&gt; "Improved", "Improved", "Improved", "Improved", "I…
$ lease_commence_date &lt;int&gt; 1980, 1978, 1977, 1986, 1986, 1979, 1980, 1980, 19…
$ resale_price        &lt;dbl&gt; 253000, 270000, 283000, 305000, 320000, 325000, 32…
$ remaining_lease     &lt;dbl&gt; 66, 64, 63, 72, 72, 65, 66, 66, 65, 66, 66, 65, 66…</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(<span class="fu">head</span>(extract_data), </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">class=</span> <span class="st">"compact"</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">rownames =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">width=</span><span class="st">"100%"</span>, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">options =</span> <span class="fu">list</span>(<span class="at">pageLength =</span> <span class="dv">10</span>,<span class="at">scrollX=</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="htmlwidget-2f3431f25429d448f9df" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-2f3431f25429d448f9df">{"x":{"filter":"none","vertical":false,"data":[["2013-01-01","2013-01-01","2013-01-01","2013-01-01","2013-01-01","2013-01-01"],["ANG MO KIO","ANG MO KIO","ANG MO KIO","ANG MO KIO","ANG MO KIO","ANG MO KIO"],["2 ROOM","2 ROOM","2 ROOM","3 ROOM","3 ROOM","3 ROOM"],["510","314","323","170","174","445"],["ANG MO KIO AVE 8","ANG MO KIO AVE 3","ANG MO KIO AVE 3","ANG MO KIO AVE 4","ANG MO KIO AVE 4","ANG MO KIO AVE 10"],["01 TO 03","01 TO 03","04 TO 06","07 TO 09","01 TO 03","04 TO 06"],[44,44,44,61,60,67],["Improved","Improved","Improved","Improved","Improved","New Generation"],[1980,1978,1977,1986,1986,1979],[253000,270000,283000,305000,320000,325000],[66,64,63,72,72,65]],"container":"<table class=\"compact\">\n  <thead>\n    <tr>\n      <th>month<\/th>\n      <th>town<\/th>\n      <th>flat_type<\/th>\n      <th>block<\/th>\n      <th>street_name<\/th>\n      <th>storey_range<\/th>\n      <th>floor_area_sqm<\/th>\n      <th>flat_model<\/th>\n      <th>lease_commence_date<\/th>\n      <th>resale_price<\/th>\n      <th>remaining_lease<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"scrollX":true,"columnDefs":[{"className":"dt-right","targets":[6,8,9,10]},{"name":"month","targets":0},{"name":"town","targets":1},{"name":"flat_type","targets":2},{"name":"block","targets":3},{"name":"street_name","targets":4},{"name":"storey_range","targets":5},{"name":"floor_area_sqm","targets":6},{"name":"flat_model","targets":7},{"name":"lease_commence_date","targets":8},{"name":"resale_price","targets":9},{"name":"remaining_lease","targets":10}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(extract_data[<span class="fu">duplicated</span>(extract_data),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   610 obs. of  11 variables:
 $ month              : Date, format: "2013-03-01" "2013-04-01" ...
 $ town               : chr  "JURONG EAST" "BUKIT BATOK" "TOA PAYOH" "TOA PAYOH" ...
 $ flat_type          : chr  "3 ROOM" "3 ROOM" "3 ROOM" "5 ROOM" ...
 $ block              : chr  "252" "523" "57" "81" ...
 $ street_name        : chr  "JURONG EAST ST 24" "BT BATOK ST 52" "LOR 5 TOA PAYOH" "LOR 4 TOA PAYOH" ...
 $ storey_range       : chr  "01 TO 03" "01 TO 03" "01 TO 03" "19 TO 21" ...
 $ floor_area_sqm     : num  67 60 61 122 60 146 74 67 67 93 ...
 $ flat_model         : chr  "New Generation" "Improved" "Standard" "Improved" ...
 $ lease_commence_date: int  1985 1987 1973 1997 1986 1991 1984 1972 1979 2010 ...
 $ resale_price       : num  343000 315000 320000 880000 300000 720000 388000 292000 356000 600000 ...
 $ remaining_lease    : num  71 73 59 83 72 77 70 58 65 96 ...</code></pre>
</div>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(extract_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     month                town            flat_type            block          
 Min.   :2013-01-01   Length:238519      Length:238519      Length:238519     
 1st Qu.:2016-07-01   Class :character   Class :character   Class :character  
 Median :2019-05-01   Mode  :character   Mode  :character   Mode  :character  
 Mean   :2019-01-13                                                           
 3rd Qu.:2021-10-01                                                           
 Max.   :2023-12-01                                                           
 street_name        storey_range       floor_area_sqm    flat_model       
 Length:238519      Length:238519      Min.   : 31.00   Length:238519     
 Class :character   Class :character   1st Qu.: 76.00   Class :character  
 Mode  :character   Mode  :character   Median : 94.00   Mode  :character  
                                       Mean   : 96.99                     
                                       3rd Qu.:112.00                     
                                       Max.   :280.00                     
 lease_commence_date  resale_price     remaining_lease
 Min.   :1966        Min.   : 140000   Min.   :42.00  
 1st Qu.:1984        1st Qu.: 360000   1st Qu.:64.00  
 Median :1993        Median : 447000   Median :74.00  
 Mean   :1994        Mean   : 478311   Mean   :74.66  
 3rd Qu.:2003        3rd Qu.: 563000   3rd Qu.:85.00  
 Max.   :2022        Max.   :1500000   Max.   :98.00  </code></pre>
</div>
</div>
</div>
<div id="tabset-2-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-5-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">descr</span>(extract_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Non-numerical variable(s) ignored: month, town, flat_type, block, street_name, storey_range, flat_model</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  
extract_data  
N: 238519  

                    floor_area_sqm   lease_commence_date   remaining_lease   resale_price
----------------- ---------------- --------------------- ----------------- --------------
             Mean            96.99               1994.22             74.66      478310.91
          Std.Dev            24.17                 13.32             12.97      160952.26
              Min            31.00               1966.00             42.00      140000.00
               Q1            76.00               1984.00             64.00      360000.00
           Median            94.00               1993.00             74.00      447000.00
               Q3           112.00               2003.00             85.00      563000.00
              Max           280.00               2022.00             98.00     1500000.00
              MAD            26.69                 13.34             14.83      143812.20
              IQR            36.00                 19.00             21.00      203000.00
               CV             0.25                  0.01              0.17           0.34
         Skewness             0.28                  0.18              0.02           1.04
      SE.Skewness             0.01                  0.01              0.01           0.01
         Kurtosis            -0.11                 -0.98             -1.04           1.28
          N.Valid        238519.00             238519.00         238519.00      238519.00
        Pct.Valid           100.00                100.00            100.00         100.00</code></pre>
</div>
</div>
</div>
</div>
</div>
<div style="background-color: #E8EAF6;    border-radius: 10px;    padding: 20px;">
<p><strong>Observation from the above:</strong></p>
<ul>
<li><p>From <code>glimpse()</code>, we can see the data types of all variables. There are four numerical variables: <em>floor_area_sqm, lease_commence_date, resale_price, remaining_lease</em>. Seven categorical variables: <em>month, town, flat_type, block, street_name, storey_range, flat_model</em>. Variable <em>town, flat_type, block, street_name, storey_range, flat_model</em> are all character-type.</p></li>
<li><p>From <code>glimpse()</code>, we can see that there are a total of 238,519 rows and 11 columns. Combining the <code>Length</code> of categorical variables seen in <code>summary()</code> and the <code>N.Valid</code> from <code>descr()</code> for numerical variables, we find that each variable has 238,519 values, indicating that there are no missing values in this dataframe.</p></li>
<li><p>From <code>duplicate()</code>, we can see that there are 610 records have duplicate rows. We speculate that it is caused by duplicate data entry.</p></li>
</ul>
</div>
<p>After the above observations, we are going to process the data to make it more suitable for our subsequent analysis.</p>
<p>Step 1. Convert all character-type variables to factor-type variables so that we can analyze the distribution of the different values of categorical variables in subsequent analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all character-type variables to factor-type variables.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>extract_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(extract_data, <span class="cf">function</span>(x) {</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">is.character</span>(x)) {</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">factor</span>(x))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(x)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Step 2. Remove all the duplicate rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>extract_data <span class="ot">&lt;-</span> <span class="fu">distinct</span>(extract_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check duplicates again by the code chunk below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(extract_data[<span class="fu">duplicated</span>(extract_data),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   0 obs. of  11 variables:
 $ month              : 'Date' num(0) 
 $ town               : Factor w/ 26 levels "ANG MO KIO","BEDOK",..: 
 $ flat_type          : Factor w/ 7 levels "1 ROOM","2 ROOM",..: 
 $ block              : Factor w/ 2699 levels "1","10","100",..: 
 $ street_name        : Factor w/ 567 levels "ADMIRALTY DR",..: 
 $ storey_range       : Factor w/ 17 levels "01 TO 03","04 TO 06",..: 
 $ floor_area_sqm     : num 
 $ flat_model         : Factor w/ 21 levels "2-room","3Gen",..: 
 $ lease_commence_date: int 
 $ resale_price       : num 
 $ remaining_lease    : num </code></pre>
</div>
</div>
</section>
</section>
<section id="save-data" class="level1">
<h1>3 Save Data</h1>
<p>We will save this dataframe as a rds object for faster loading of data in the future.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(extract_data, <span class="st">"data/resale_hdb.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comfirmatory-data-analysis" class="level1">
<h1>4. Comfirmatory Data Analysis</h1>
<p>Confirmatory data analysis (CDA) is a type of data analysis that seeks to confirm or validate hypotheses or theories based on existing data. Unlike exploratory data analysis (EDA), which is more open-ended and aims to discover patterns and relationships in data, CDA starts with specific hypotheses or models that the researcher wants to test using the data.</p>
<section id="load-processed-data" class="level2">
<h2 class="anchored" data-anchor-id="load-processed-data">4.1 Load Processed data</h2>
<p>We will reload the processed data for confirmatory data analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>resale_hdb <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/resale_hdb.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="distribution-of-numerical-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-numerical-categorical-variables">4.2 Distribution of numerical &amp; categorical variables</h2>
<p>The instruction is to analyze what factors impact the “resale_price” column in this “resale_hdb” dataset, and how visualizing the distribution of each numerical and categorical column is important for this analysis.</p>
<p>Visualizing the distribution of each column in the dataset is crucial for understanding the patterns, trends and relationships within the data that could influence the resale price.</p>
<ul>
<li><p>Identify skewness and outliers: Plotting the distribution of numerical columns like “floor_area_sqm” and “resale_price” can reveal if the data is skewed or contains outliers. Skewed distributions or extreme outliers can distort analyses and should be properly handled.</p></li>
<li><p>Spot patterns and trends: Visualizing categorical columns like “flat_type”, “town” and “flat_model” as bar charts or pie charts can uncover which categories are most frequent. Segmenting resale prices by these categories could reveal useful patterns, like certain towns or flat models being associated with higher prices.</p></li>
</ul>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a larger plot window size</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width=</span><span class="dv">12</span>, <span class="at">repr.plot.height=</span><span class="dv">12</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution of numerical columns</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>), <span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>))  <span class="co"># Set the layout of the plots and reduce margins</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>numerical_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"floor_area_sqm"</span>, <span class="st">"lease_commence_date"</span>, <span class="st">"resale_price"</span>, <span class="st">"remaining_lease"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> numerical_cols) {</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hist</span>(resale_hdb[[col]], <span class="at">main=</span>col, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">col=</span><span class="st">"skyblue"</span>, <span class="at">border=</span><span class="st">"white"</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the distribution of categorical columns</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"month"</span>, <span class="st">"town"</span>, <span class="st">"flat_type"</span>,  <span class="st">"storey_range"</span>, <span class="st">"flat_model"</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> categorical_cols) {</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">barplot</span>(<span class="fu">table</span>(resale_hdb[[col]]), <span class="at">main=</span>col, <span class="at">col=</span><span class="st">"skyblue"</span>, <span class="at">border=</span><span class="st">"white"</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Observations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Based on the distributions shown in the plots, several observations can be made about the resale HDB dataset:</p>
<ol type="1">
<li>Most of the flats have a floor area between 60-80 square meters, with some larger flats over 100 sqm. The distribution is right-skewed.</li>
<li>The lease commencement dates are concentrated in the late 1970s through 1990s, with peaks around 1980 and fewer flats from 2000 onwards. This suggests an older housing stock.</li>
<li>Resale prices are widely distributed from under $200,000 to over $1,000,000, but most fall between $200,000-600,000. A few high-priced outliers are visible.</li>
<li>The remaining lease years are spread out, with most between 50-100 years, but some below 50 years. Lease length likely impacts resale values.</li>
<li>The transaction months span 2013-2021, with the most sales in 2013, fewer in 2017, and a rebound in early 2021. Market conditions seem to fluctuate over time.</li>
<li>Most of the transactions are for flats in Ang Mo Kio town, with fewer in Geylang and Sengkang. Location is likely a price factor.</li>
<li>The majority of flats are 3 ROOM, with fewer 1 ROOM and 5 ROOM. Flat type and size probably influence prices. Most flats fall in the 01 TO 03 and 04 TO 06 storey ranges, with the fewest in the highest 37 TO 39 range. Floor level may affect prices.</li>
<li>Flat models are split mainly between Improved, New Generation and a small number of simplified flats. The flat model could correlate with resale prices.</li>
</ol>
</div>
</div>
</section>
<section id="correlation-matrix-of-munerical-variables" class="level2">
<h2 class="anchored" data-anchor-id="correlation-matrix-of-munerical-variables">4.3 Correlation matrix of munerical variables</h2>
<p>In order to perform further analysis and modelling, it is essential to explore the correlation between variables. - When building predictive models, correlation plots can guide feature selection by highlighting variables that are strongly correlated with the target variable (like resale price). Strongly correlated predictors may be good candidates to include in the model. - If two variables are very strongly correlated, they may provide redundant information. Correlation plots can identify opportunities to drop one of the variables or combine them into a single feature, simplifying the model.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Numerical Variable</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Categorical Variable</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out numerical columns</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>numerical_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"floor_area_sqm"</span>, <span class="st">"lease_commence_date"</span>, <span class="st">"resale_price"</span>, <span class="st">"remaining_lease"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>numerical_data <span class="ot">&lt;-</span> resale_hdb[numerical_cols]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation matrix</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numerical_data)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a heatmap of the correlation matrix</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>correlation_melted <span class="ot">&lt;-</span> <span class="fu">melt</span>(correlation_matrix)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(correlation_melted, <span class="fu">aes</span>(Var1, Var2, <span class="at">fill=</span>value)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color=</span><span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">low=</span><span class="st">"blue"</span>, <span class="at">high=</span><span class="st">"red"</span>, <span class="at">mid=</span><span class="st">"white"</span>, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">midpoint=</span><span class="dv">0</span>, <span class="at">limit=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>), <span class="at">space=</span><span class="st">"Lab"</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name=</span><span class="st">"Correlation"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In summary, if we were building a model to predict resale prices, a good initial set of features based on this correlation analysis would be:</p>
<ul>
<li>Floor area</li>
<li>Remaining lease OR lease commencement date (but not both) The low-to-moderate correlations suggest these features capture somewhat independent information relevant to predicting prices. Of course, other factors like location, storey, and flat model would also be worth considering in combination with these.</li>
</ul>
<p>The critical takeaway is that very strongly correlated predictors (like remaining lease and commencement date) should not be included together as they provide redundant information and can cause model instability. The correlation matrix allows us to be parsimonious and strategic in selecting an optimal set of features.</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the necessary package</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rcompanion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rcompanion' was built under R version 4.3.3</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify the categorical variables</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"flat_type"</span>, <span class="st">"storey_range"</span>, <span class="st">"town"</span>, <span class="st">"flat_model"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an empty matrix to store Cramér's V values</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>cramer_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow =</span> <span class="fu">length</span>(categorical_vars), <span class="at">ncol =</span> <span class="fu">length</span>(categorical_vars),</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">dimnames =</span> <span class="fu">list</span>(categorical_vars, categorical_vars))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate Cramér's V</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>cramer_v <span class="ot">&lt;-</span> <span class="cf">function</span>(cont_table) {</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  chi_sq <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(cont_table)<span class="sc">$</span>statistic</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">sum</span>(cont_table)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  min_dim <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">nrow</span>(cont_table), <span class="fu">ncol</span>(cont_table))</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(chi_sq <span class="sc">/</span> (n <span class="sc">*</span> (min_dim <span class="sc">-</span> <span class="dv">1</span>)))</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform chi-square tests and calculate Cramér's V for each pair of variables</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(categorical_vars)<span class="sc">-</span><span class="dv">1</span>)) {</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> (i<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">length</span>(categorical_vars)) {</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>    var1 <span class="ot">&lt;-</span> categorical_vars[i]</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    var2 <span class="ot">&lt;-</span> categorical_vars[j]</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a contingency table</span></span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>    cont_table <span class="ot">&lt;-</span> <span class="fu">table</span>(resale_hdb[[var1]], resale_hdb[[var2]])</span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Perform chi-square test</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>    chi_sq <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(cont_table)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If the association is significant (p &lt; 0.05), calculate Cramér's V</span></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (chi_sq<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>) {</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>      cramer_val <span class="ot">&lt;-</span> <span class="fu">cramer_v</span>(cont_table)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>      cramer_matrix[var1, var2] <span class="ot">&lt;-</span> cramer_val</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>      cramer_matrix[var2, var1] <span class="ot">&lt;-</span> cramer_val</span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect

Warning in chisq.test(cont_table): Chi-squared approximation may be incorrect</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>short_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Type"</span>, <span class="st">"Storey"</span>, <span class="st">"Town"</span>, <span class="st">"Model"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a heatmap of the Cramér's V matrix with shorter labels</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(cramer_matrix, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"white"</span>, <span class="st">"red"</span>))(<span class="dv">100</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Cramér's V Matrix"</span>,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Categorical Variables"</span>,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Categorical Variables"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">scale =</span> <span class="st">"none"</span>,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">margins =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">labRow =</span> short_labels,  <span class="co"># Use shorter labels for rows</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">labCol =</span> short_labels,  <span class="co"># Use shorter labels for columns</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.axis =</span> <span class="fl">0.8</span>,</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>The strong association between “town” and “flat_model” suggests that certain towns may have distinct distributions of flat models. This could indicate that specific flat models are more prevalent in certain areas.</li>
<li>The moderate associations of “storey_range” with “flat_type” and “flat_model” imply that the storey range of a flat may be related to its type and model. For example, certain flat types or models might be more common in specific storey ranges. The relatively weaker associations of “flat_type” with other variables suggest that the flat type may have less influence on the other categorical variables compared to the relationships among the other variables.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">4.4 Hypothesis Testing</h2>
<section id="anova-test-town-vs.-resale-price" class="level3">
<h3 class="anchored" data-anchor-id="anova-test-town-vs.-resale-price">4.4.1 ANOVA test: Town vs.&nbsp;Resale Price</h3>
<p>The ANOVA test in this context helps us understand the impact of the factors on the ‘resale_price’ variable. The code chunk below test on the the variable “town” and “resale_price”</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(resale_price <span class="sc">~</span> town, <span class="at">data=</span>resale_hdb)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize ANOVA results</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>plot_ANOVA <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resale_hdb, <span class="fu">aes</span>(<span class="at">x=</span>town, <span class="at">y=</span>resale_price)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"ANOVA: Town vs. Resale Price"</span>, <span class="at">x=</span><span class="st">"Town"</span>, <span class="at">y=</span><span class="st">"Resale Price"</span>) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_ANOVA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of ANOVA results</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                Df    Sum Sq   Mean Sq F value Pr(&gt;F)    
town            25 7.262e+14 2.905e+13    1269 &lt;2e-16 ***
Residuals   237883 5.444e+15 2.289e+10                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A small p-value from an ANOVA test indicates that there is strong evidence against the null hypothesis, which suggests that the mean ‘resale_price’ is the same across all ‘towns’. In other words, the p-value indicates that the ‘town’ variable significantly affects the ‘resale_price’. Therefore, with a very small p-value, we would reject the null hypothesis and conclude that there is a statistically significant difference in ‘resale_price’ among the different ‘towns’.</p>
</section>
<section id="non-parametric-test-of-town-and-flat-type" class="level3">
<h3 class="anchored" data-anchor-id="non-parametric-test-of-town-and-flat-type">4.4.2 Non-parametric Test of town and flat type</h3>
<p>The code chunk below is Pearson’s chi-squared test, which assesses the association between two categorical variables. It allows us to explore the relationship between variables.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>plot_barstats_town <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">metric =</span> <span class="st">"town"</span>, <span class="at">minvisitors =</span> <span class="dv">30</span>, <span class="at">testtype =</span> <span class="st">"np"</span>, <span class="at">conf =</span> <span class="fl">0.95</span>) {</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  metric_text <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    metric <span class="sc">==</span> <span class="st">"remaining_lease"</span> <span class="sc">~</span> <span class="st">"Remaining Lease"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    metric <span class="sc">==</span> <span class="st">"storey_range"</span> <span class="sc">~</span> <span class="st">"Storey Range"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    metric <span class="sc">==</span> <span class="st">"flat_type"</span> <span class="sc">~</span> <span class="st">"Flat Type"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> metric</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  hdbdata_barstats <span class="ot">&lt;-</span> resale_hdb</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  hdbdata_barstats <span class="sc">%&gt;%</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggbarstats</span>(<span class="at">x =</span> flat_type, <span class="at">y =</span> <span class="sc">!!</span><span class="fu">sym</span>(metric),</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">xlab =</span> <span class="st">"Flat Type"</span>, <span class="at">ylab =</span> metric_text,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">type =</span> testtype, <span class="at">conf.level =</span> conf,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>               <span class="at">palette =</span> <span class="st">"Set2"</span>, <span class="at">legend =</span> <span class="st">"top"</span>) <span class="sc">+</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Flat Type"</span>, <span class="at">x =</span> <span class="st">"Town"</span>, <span class="at">y =</span> <span class="st">"Percentage"</span>) <span class="sc">+</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,<span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="dv">10</span>))</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_barstats_town</span>(<span class="at">metric =</span> <span class="st">"town"</span>, <span class="at">minvisitors =</span> <span class="dv">30</span>, <span class="at">testtype =</span> <span class="st">"np"</span>, <span class="at">conf =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
key observations from the plot:
</div>
</div>
<div class="callout-body-container callout-body">
<p>“MULTI-GENERATION” flats are more prevalent in towns like Yishun, Woodlands, and Tampines, while they are least common in towns like Bishan, Bukit Batok, and Ang Mo Kio. “EXECUTIVE” flats have a higher percentage in towns such as Pasir Ris, Serangoon, and Marine Parade, compared to other towns. Larger flat types (“5 ROOM,” “4 ROOM,” and “3 ROOM”) generally make up a significant portion of the housing distribution across all towns. Smaller flat types (“2 ROOM” and “1 ROOM”) have a relatively lower percentage across most towns, with a slightly higher presence in towns like Kallang/Whampoa, Bukit Merah, and Central Area.</p>
</div>
</div>
</section>
</section>
</section>
<section id="clustering" class="level1">
<h1>5. Clustering</h1>
<p>Clustering is an unsupervised machine learning technique that aims to group similar data points together based on their inherent characteristics or features. In this analysis, we explore two popular clustering methods, K-means clustering and latent clustering analysis, to gain insights into the patterns and structures within the housing resale prices dataset.</p>
<p>The dataset contains information about resale prices of housing units in Singapore, along with various attributes such as town, flat type, storey range, floor area, flat model, lease commence date, and remaining lease. By applying clustering techniques, we aim to uncover hidden groupings or segments within the data that share similar characteristics and pricing patterns.</p>
<section id="k-means-clustering" class="level2">
<h2 class="anchored" data-anchor-id="k-means-clustering">5.1 K-means clustering</h2>
<p>K-means clustering is a centroid-based algorithm that partitions the data into a specified number of clusters (K). It iteratively assigns each data point to the nearest centroid (cluster center) based on a distance metric, typically Euclidean distance. The algorithm optimizes the cluster assignments by minimizing the within-cluster sum of squared distances.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'factoextra' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/resale_hdb.rds"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(block, street_name))</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values and infinite/NaN values</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>missing_cols <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data)) <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>infinite_cols <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="sc">!</span><span class="fu">is.finite</span>(x)))</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Label encoding for categorical columns</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>categorical_cols <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data, is.factor)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>data_encoded <span class="ot">&lt;-</span> data</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">names</span>(data)[categorical_cols]) {</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  data_encoded[[col]] <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">factor</span>(data_encoded[[col]]))</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all columns to numeric</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>data_encoded <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">lapply</span>(data_encoded, as.numeric))</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in data_encoded</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>missing_encoded <span class="ot">&lt;-</span> <span class="fu">colSums</span>(<span class="fu">is.na</span>(data_encoded))</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">any</span>(missing_encoded <span class="sc">&gt;</span> <span class="dv">0</span>)) {</span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Columns with missing values in data_encoded:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(missing_encoded[missing_encoded <span class="sc">&gt;</span> <span class="dv">0</span>])</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"No missing values found in data_encoded.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>No missing values found in data_encoded.</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for infinite values in data_encoded</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>infinite_encoded <span class="ot">&lt;-</span> <span class="fu">sapply</span>(data_encoded, <span class="cf">function</span>(x) <span class="fu">any</span>(<span class="sc">!</span><span class="fu">is.finite</span>(x)))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">any</span>(infinite_encoded)) {</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Columns with infinite values in data_encoded:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">names</span>(data_encoded)[infinite_encoded])</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"No infinite values found in data_encoded.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>No infinite values found in data_encoded.</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the number of clusters</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co"># Determine the optimal number of clusters before running this</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run k-means clustering on the encoded data</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>km.res <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(data_encoded, <span class="at">centers =</span> k)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add cluster assignments to the original data</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>cluster <span class="ot">&lt;-</span> km.res<span class="sc">$</span>cluster</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize clusters</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(km.res, <span class="at">data =</span> data_encoded)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution for each column variable for each cluster</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create stacked bar chart for a given column</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>plot_stacked_bar <span class="ot">&lt;-</span> <span class="cf">function</span>(data, column) {</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(cluster), <span class="at">fill =</span> <span class="fu">factor</span>(<span class="fu">get</span>(column)))) <span class="sc">+</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cluster"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>, <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Distribution of"</span>, column)) <span class="sc">+</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot stacked bar charts for each categorical column</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">names</span>(data)[categorical_cols]) {</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">plot_stacked_bar</span>(data, col))</span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-23-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-23-5.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="latent-clustering-analysis" class="level2">
<h2 class="anchored" data-anchor-id="latent-clustering-analysis">5.2 Latent Clustering Analysis</h2>
<p>On the other hand, latent clustering analysis, also known as model-based clustering or finite mixture modeling, assumes that the data is generated from a mixture of underlying probability distributions. Each cluster is represented by a different distribution, and the goal is to identify the parameters of these distributions and assign each data point to the most likely cluster. Latent clustering analysis provides a probabilistic framework for modeling the data and allows for the estimation of the optimal number of clusters based on statistical criteria.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poLCA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'poLCA' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: scatterplot3d</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/resale_hdb.rds"</span>)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the "block" and "street_name" columns</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(block, street_name))</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Discretize continuous variables</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>resale_price_bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>resale_price, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">200000</span>, <span class="dv">400000</span>, <span class="dv">600000</span>, <span class="cn">Inf</span>),</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>, <span class="st">"Very High"</span>))</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>floor_area_sqm_bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>floor_area_sqm, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">150</span>, <span class="cn">Inf</span>),</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>                               <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Small"</span>, <span class="st">"Medium"</span>, <span class="st">"Large"</span>, <span class="st">"Very Large"</span>))</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>remaining_lease_bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>remaining_lease, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">75</span>, <span class="dv">100</span>, <span class="cn">Inf</span>),</span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Short"</span>, <span class="st">"Medium"</span>, <span class="st">"Long"</span>, <span class="st">"Very Long"</span>))</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert categorical variables to factors and recode them as positive integers</span></span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"town"</span>, <span class="st">"flat_type"</span>, <span class="st">"storey_range"</span>, <span class="st">"flat_model"</span>,</span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"lease_commence_date"</span>, <span class="st">"resale_price_bin"</span>, <span class="st">"floor_area_sqm_bin"</span>, <span class="st">"remaining_lease_bin"</span>)</span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> categorical_vars) {</span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  data[[var]] <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">factor</span>(data[[var]]))</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform latent clustering analysis</span></span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>lca_model <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(<span class="at">formula =</span> <span class="fu">cbind</span>(town, flat_type, storey_range, flat_model,</span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a>                                   lease_commence_date, resale_price_bin,</span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a>                                   floor_area_sqm_bin, remaining_lease_bin) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> data, <span class="at">nclass =</span> <span class="dv">3</span>, <span class="at">maxiter =</span> <span class="dv">1000</span>, <span class="at">graphs =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$town
           Pr(1)  Pr(2)  Pr(3)  Pr(4)  Pr(5)  Pr(6)  Pr(7)  Pr(8)  Pr(9) Pr(10)
class 1:  0.1051 0.1185 0.0170 0.0556 0.0518 0.0132 0.0025 0.0154 0.0071 0.0475
class 2:  0.0156 0.0362 0.0284 0.0323 0.0224 0.0473 0.0037 0.0033 0.0729 0.0092
class 3:  0.0155 0.0167 0.0019 0.0233 0.0514 0.0473 0.0000 0.0086 0.0411 0.0178
          Pr(11) Pr(12) Pr(13) Pr(14) Pr(15) Pr(16) Pr(17) Pr(18) Pr(19) Pr(20)
class 1:  0.0510 0.0509 0.0312 0.0445 0.0503 0.0150 0.0015 0.0000 0.0402 0.0000
class 2:  0.0136 0.0568 0.0200 0.0954 0.0172 0.0039 0.0636 0.0515 0.0105 0.0310
class 3:  0.0154 0.0379 0.0109 0.0578 0.0277 0.0000 0.0086 0.1645 0.0430 0.0519
          Pr(21) Pr(22) Pr(23) Pr(24) Pr(25) Pr(26)
class 1:  0.0000 0.0309 0.0585 0.0560 0.0376 0.0986
class 2:  0.0784 0.0205 0.0978 0.0210 0.0964 0.0512
class 3:  0.1807 0.0030 0.0280 0.0187 0.0734 0.0552

$flat_type
           Pr(1)  Pr(2)  Pr(3)  Pr(4)  Pr(5)  Pr(6) Pr(7)
class 1:  0.0014 0.0217 0.6807 0.2962 0.0000 0.0000 0e+00
class 2:  0.0000 0.0000 0.0000 0.2788 0.5502 0.1702 8e-04
class 3:  0.0000 0.0340 0.1471 0.8185 0.0004 0.0000 0e+00

$storey_range
           Pr(1)  Pr(2)  Pr(3)  Pr(4)  Pr(5)  Pr(6)  Pr(7)  Pr(8)  Pr(9) Pr(10)
class 1:  0.2201 0.2759 0.2405 0.1993 0.0438 0.0126 0.0054 0.0022 0.0002 0.0000
class 2:  0.1865 0.2359 0.2133 0.1860 0.0933 0.0414 0.0174 0.0124 0.0058 0.0035
class 3:  0.1241 0.1771 0.1781 0.1760 0.1487 0.0788 0.0341 0.0260 0.0190 0.0131
          Pr(11) Pr(12) Pr(13) Pr(14) Pr(15) Pr(16) Pr(17)
class 1:  0.0000 0.0000 0.0000 0.0000  0e+00  0e+00  0e+00
class 2:  0.0012 0.0011 0.0011 0.0006  1e-04  1e-04  0e+00
class 3:  0.0074 0.0070 0.0061 0.0027  9e-04  6e-04  2e-04

$flat_model
           Pr(1) Pr(2)  Pr(3)  Pr(4)  Pr(5)  Pr(6) Pr(7)  Pr(8)  Pr(9) Pr(10)
class 1:  0.0000 0e+00 0.0004 0.0000 0.0000 0.2497 0e+00 0.0000 0.1097  0.000
class 2:  0.0000 2e-04 0.0035 0.0856 0.0145 0.3869 3e-04 0.0637 0.2892  0.004
class 3:  0.0012 0e+00 0.0000 0.0000 0.0287 0.0000 0e+00 0.0000 0.6879  0.000
          Pr(11) Pr(12) Pr(13) Pr(14) Pr(15) Pr(16) Pr(17) Pr(18) Pr(19) Pr(20)
class 1:  0.0000  0e+00 0.4442 0.0000 0.0000  0e+00 0.1332 0.0609 0.0018 0.0000
class 2:  0.0005  8e-04 0.0000 0.1232 0.0003  2e-04 0.0000 0.0250 0.0000 0.0000
class 3:  0.0516  0e+00 0.0000 0.2171 0.0012  0e+00 0.0048 0.0000 0.0000 0.0075
          Pr(21)
class 1:   0.000
class 2:   0.002
class 3:   0.000

$lease_commence_date
          Pr(1) Pr(2)  Pr(3)  Pr(4)  Pr(5)  Pr(6)  Pr(7)  Pr(8)  Pr(9) Pr(10)
class 1:  3e-04 0.017 0.0043 0.0168 0.0281 0.0157 0.0149 0.0194 0.0325 0.0346
class 2:  0e+00 0.000 0.0000 0.0001 0.0001 0.0000 0.0001 0.0001 0.0015 0.0049
class 3:  0e+00 0.000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
          Pr(11) Pr(12) Pr(13) Pr(14) Pr(15) Pr(16) Pr(17) Pr(18) Pr(19) Pr(20)
class 1:  0.0463 0.0386 0.0826 0.0665 0.0664 0.0457 0.0267 0.0390 0.0848 0.1350
class 2:  0.0056 0.0057 0.0091 0.0069 0.0066 0.0044 0.0053 0.0105 0.0463 0.0491
class 3:  0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
          Pr(21) Pr(22) Pr(23) Pr(24) Pr(25) Pr(26) Pr(27) Pr(28) Pr(29) Pr(30)
class 1:  0.0571 0.0589 0.0480 0.0112 0.0014 0.0000 0.0014 0.0031 0.0011  0.001
class 2:  0.0249 0.0308 0.0567 0.0507 0.0156 0.0025 0.0400 0.0499 0.0119  0.037
class 3:  0.0000 0.0000 0.0000 0.0000 0.0002 0.0000 0.0000 0.0017 0.0012  0.000
          Pr(31) Pr(32) Pr(33) Pr(34) Pr(35) Pr(36) Pr(37) Pr(38) Pr(39) Pr(40)
class 1:  0.0007 0.0000 0.0006 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
class 2:  0.0558 0.0535 0.0516 0.0551 0.0442 0.0557 0.0322 0.0441 0.0218 0.0097
class 3:  0.0042 0.0345 0.0269 0.0193 0.0343 0.0441 0.0388 0.0458 0.0336 0.0203
          Pr(41) Pr(42) Pr(43) Pr(44) Pr(45) Pr(46) Pr(47) Pr(48) Pr(49) Pr(50)
class 1:  0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
class 2:  0.0062 0.0002 0.0091 0.0005 0.0005 0.0080 0.0047 0.0072 0.0042 0.0195
class 3:  0.0233 0.0120 0.0152 0.0278 0.0218 0.0307 0.0746 0.0784 0.0541 0.1323
          Pr(51) Pr(52) Pr(53) Pr(54) Pr(55) Pr(56)
class 1:  0.0000 0.0000 0.0000 0.0000  0e+00      0
class 2:  0.0155 0.0123 0.0100 0.0021  1e-04      0
class 3:  0.0771 0.0620 0.0648 0.0205  4e-04      0

$resale_price_bin
           Pr(1)  Pr(2)  Pr(3)  Pr(4)
class 1:  0.0059 0.7694 0.2147 0.0099
class 2:  0.0000 0.1372 0.5460 0.3169
class 3:  0.0004 0.2632 0.5231 0.2133

$floor_area_sqm_bin
           Pr(1)  Pr(2)  Pr(3)  Pr(4)
class 1:  0.0213 0.9719 0.0065 0.0003
class 2:  0.0000 0.0000 0.9756 0.0244
class 3:  0.0335 0.9665 0.0000 0.0000

$remaining_lease_bin
           Pr(1)  Pr(2)  Pr(3)
class 1:  0.0550 0.9432 0.0018
class 2:  0.0002 0.4771 0.5227
class 3:  0.0000 0.0176 0.9824

Estimated class population shares 
 0.316 0.4423 0.2417 
 
Predicted class memberships (by modal posterior prob.) 
 0.3152 0.4431 0.2417 
 
========================================================= 
Fit for 3 latent classes: 
========================================================= 
number of observations: 237909 
number of estimated parameters: 392 
residual degrees of freedom: 237517 
maximum log-likelihood: -2980507 
 
AIC(3): 5961798
BIC(3): 5965866
G^2(3): 1597035 (Likelihood ratio/deviance statistic) 
X^2(3): 59240209478 (Chi-square goodness of fit) 
 </code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the cluster assignments</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>cluster <span class="ot">&lt;-</span> lca_model<span class="sc">$</span>predclass</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summary</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lca_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Length Class      Mode   
llik                1 -none-     numeric
attempts            1 -none-     numeric
probs.start         8 -none-     list   
probs               8 -none-     list   
probs.se            8 -none-     list   
P.se                3 -none-     numeric
posterior      713727 -none-     numeric
predclass      237909 -none-     numeric
P                   3 -none-     numeric
numiter             1 -none-     numeric
probs.start.ok      1 -none-     logical
coeff               1 -none-     logical
coeff.se            1 -none-     logical
coeff.V             1 -none-     logical
eflag               1 -none-     logical
npar                1 -none-     numeric
aic                 1 -none-     numeric
bic                 1 -none-     numeric
Nobs                1 -none-     numeric
Chisq               1 -none-     numeric
predcell           10 data.frame list   
Gsq                 1 -none-     numeric
y                   8 data.frame list   
x                   1 data.frame list   
N                   1 -none-     numeric
maxiter             1 -none-     numeric
resid.df            1 -none-     numeric
time                1 difftime   numeric
call                6 -none-     call   </code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution for each column variable for each cluster</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create stacked bar chart for a given column</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>plot_stacked_bar <span class="ot">&lt;-</span> <span class="cf">function</span>(data, column) {</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(cluster), <span class="at">fill =</span> <span class="fu">factor</span>(<span class="fu">get</span>(column)))) <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cluster"</span>, <span class="at">y =</span> <span class="st">"Proportion"</span>, <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Distribution of"</span>, column)) <span class="sc">+</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot stacked bar charts for each categorical variable</span></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> categorical_vars) {</span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">plot_stacked_bar</span>(data, var))</span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-24-8.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="decision-tree-analysis" class="level1">
<h1>6 Decision tree Analysis</h1>
<p>The HDB Resale Price dataset contains information about resale transactions of public housing properties in Singapore. The dataset includes various features such as the month of the transaction, town, flat type, storey range, floor area, flat model, lease commence date, and the resale price. The goal is to build predictive models that can estimate the resale price of HDB flats based on these features.</p>
<section id="regression-tree" class="level2">
<h2 class="anchored" data-anchor-id="regression-tree">6.1 Regression Tree</h2>
<p>The decision tree model for the HDB Resale Price dataset will start with the entire dataset at the root node and then recursively split the data based on the features that provide the most information gain. The splitting process continues until a stopping criterion is met, such as reaching a maximum depth or a minimum number of samples in a leaf node. The resulting tree structure will allow us to make predictions by traversing the tree based on the feature values of a given HDB flat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, rpart, rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/resale_hdb.rds"</span>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the "block" and "street_name" columns</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">subset</span>(data, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(block, street_name))</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming your dataset is named 'data'</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert relevant columns to factors</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>town <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>town)</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>flat_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>flat_type)</span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>storey_range <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>storey_range)</span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>flat_model <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>flat_model)</span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the decision tree model</span></span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">rpart</span>(resale_price <span class="sc">~</span> ., <span class="at">data =</span> data, <span class="at">method =</span> <span class="st">"anova"</span>)</span>
<span id="cb68-20"><a href="#cb68-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-21"><a href="#cb68-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the decision tree</span></span>
<span id="cb68-22"><a href="#cb68-22" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(model, <span class="at">main =</span> <span class="st">"Decision Tree for Resale Price"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex04_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="shiny-app-prototype-design" class="level1">
<h1>7. Shiny App Prototype Design</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-4051744684.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption"><img src="images/clipboard-3101647271.png" class="img-fluid figure-img"></figcaption>
</figure>
</div>
<p><img src="images/clipboard-2277921120.png" class="img-fluid"></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>